"""Ajout categorie

Revision ID: 09ac3171ba17
Revises: 346024548c1b
Create Date: 2021-04-18 18:58:18.386382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ac3171ba17'
down_revision = '346024548c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('categorie', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'categorie')
    # ### end Alembic commands ###
