"""Add Product table

Revision ID: 346024548c1b
Revises: 3b984a3b0939
Create Date: 2021-04-17 13:36:31.561903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '346024548c1b'
down_revision = '3b984a3b0939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('photos', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('promo_price', sa.Numeric(), nullable=True),
    sa.Column('price_type', sa.Enum('kilo', 'unite', name='pricetype'), nullable=False),
    sa.Column('visibility', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
