"""Horaire table

Revision ID: 3b984a3b0939
Revises: d2ed66fb264d
Create Date: 2021-04-15 13:32:55.143323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b984a3b0939'
down_revision = 'd2ed66fb264d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horaire',
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('open', sa.String(), nullable=True),
    sa.Column('close', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('day')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horaire')
    # ### end Alembic commands ###
