"""Ajout Contact

Revision ID: 53e9c36ef790
Revises: b414a3bc46c0
Create Date: 2021-05-13 20:04:07.992930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e9c36ef790'
down_revision = 'b414a3bc46c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('address_city', sa.String(), server_default='B-5310 Leuze (Nam.)', nullable=False),
        sa.Column('address_street', sa.String(), server_default='Chaussée de Namur 301', nullable=False),
        sa.Column('email', sa.String(), server_default='info@boucherie-vangeebergen.be', nullable=False),
        sa.Column('facebook', sa.String(), server_default='https://www.facebook.com/boucherievangeebergen/', nullable=False),
        sa.Column('phone_mobile', sa.String(), server_default='0477 86 07 92', nullable=False),
        sa.Column('phone_office', sa.String(), server_default='081 40 06 16', nullable=False),
        sa.Column('tva', sa.String(), server_default='BE 0700.234.189', nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
