version: "3.6"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    command: npm run serve
    volumes:
      - ./web/src:/app/src
    environment:
      - VUE_APP_DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - api
  api:
    build: ./api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --root-path /api --reload
    volumes:
      - ./api:/api
      - images:/images
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE=${ACCESS_TOKEN_EXPIRE}
    depends_on:
      - db
  caddy:
    build: ./caddy
    command: caddy run
    volumes:
      - caddy_data:/data
      - images:/images
    environment:
      - WEB_PORT=${WEB_PORT}
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
      - "${WEB_PORT_HTTP}:80"
    depends_on:
      - api
      - web

volumes:
  postgres_data: {}
  caddy_data: {}
  images: {}
