version: "3"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: ./web
    command: flask run -h 0.0.0.0
    volumes:
      - ./web:/app
    ports:
      - "${WEB_PORT}:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
    depends_on:
      - api
  api:
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db:5432/postgres
      - POSTGRES_DB=${DB_NAME}
    depends_on:
      - db
volumes:
  postgres_data: {}
