version: "3.6"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - db_net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  web:
    build:
      context: ./web
      args:
        - VUE_APP_DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - caddy_net
    depends_on:
      - api
    restart: unless-stopped
  api:
    build: ./api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --root-path /api
    volumes:
      - images:/images
    networks:
      - caddy_net
      - db_net
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE=${ACCESS_TOKEN_EXPIRE}
    depends_on:
      - db
    restart: unless-stopped
  caddy:
    build: ./caddy
    command: caddy run
    volumes:
      - caddy_data:/data
      - images:/images
    networks:
      - caddy_net
    environment:
      - WEB_PORT=${WEB_PORT}
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
      - "${WEB_PORT_HTTP}:80"
    depends_on:
      - api
      - web
    restart: unless-stopped

volumes:
  postgres_data: {}
  caddy_data: {}
  images: {}

networks:
  db_net: {}
  caddy_net: {}
