version: "3"
   
services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - web_postgres_data:/var/lib/postgresql/data
  web:
    build: ./src
    command: echo server running
    volumes:
      - ./src:/app
    ports:
      - "${WEB_PORT}:8000"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    depends_on:
      - db
