version: "3"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: ./src
    command: flask run -h 0.0.0.0
    volumes:
      - ./src:/app
    ports:
      - "${WEB_PORT}:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    depends_on:
      - db
volumes:
  postgres_data: {}
