name: CD

on:
  push:
    branches: [dev]

jobs:
  deploy:
    if: github.ref == 'refs/heads/dev'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: | 
            cd ${{ secrets.PROJECT_PATH }}
            git pull
            make compose_file=docker-compose.prod.yml build
            make compose_file=docker-compose.prod.yml upgrade

